// Mock product catalogue — 40 products across 5 categories
(function () {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  const img = (id) => `https://picsum.photos/seed/nova${id}/600/600`;

  const P = [
    // ---------- Electronics ----------
    { id: 1, name: "Aurora Wireless Headphones", category: "Electronics", subcategory: "Audio", price: 149, originalPrice: 199, rating: 4.6, reviewCount: 1240, brand: "Sonique", colors: ["#111","#e5e5e5","#ff5b2e"], sizes: [], inStock: true, stockCount: 42, isNew: true, isFeatured: true, salesCount: 890, tags: ["wireless","bluetooth","noise-cancelling"], description: "Studio-grade wireless headphones with 40h battery and active noise cancelling." },
    { id: 2, name: "Nimbus Smartwatch Pro", category: "Electronics", subcategory: "Wearables", price: 299, originalPrice: 349, rating: 4.4, reviewCount: 890, brand: "Nimbus", colors: ["#111","#c0c0c0","#ffd166"], sizes: ["40mm","44mm"], inStock: true, stockCount: 18, isNew: false, isFeatured: true, salesCount: 1200, tags: ["fitness","gps","health"], description: "GPS smartwatch with ECG, SpO2, and 7-day battery." },
    { id: 3, name: "Photon 4K Action Camera", category: "Electronics", subcategory: "Cameras", price: 349, originalPrice: 399, rating: 4.7, reviewCount: 512, brand: "Photon", colors: ["#111"], sizes: [], inStock: true, stockCount: 22, isNew: true, isFeatured: false, salesCount: 430, tags: ["4k","waterproof","travel"], description: "Rugged 4K/120fps action cam with in-body stabilization." },
    { id: 4, name: "Pulse Wireless Earbuds", category: "Electronics", subcategory: "Audio", price: 79, originalPrice: 119, rating: 4.2, reviewCount: 2200, brand: "Sonique", colors: ["#fff","#111"], sizes: [], inStock: true, stockCount: 300, isNew: false, isFeatured: false, salesCount: 3400, tags: ["earbuds","bluetooth"], description: "Snug true-wireless earbuds with 24h case." },
    { id: 5, name: "Volt Portable Charger 20K", category: "Electronics", subcategory: "Accessories", price: 39, originalPrice: 59, rating: 4.5, reviewCount: 780, brand: "Volt", colors: ["#111","#fff"], sizes: [], inStock: true, stockCount: 500, isNew: false, isFeatured: false, salesCount: 2100, tags: ["battery","usb-c"], description: "20,000mAh USB-C PD 65W power bank." },
    { id: 6, name: "Orbit Mechanical Keyboard", category: "Electronics", subcategory: "Peripherals", price: 129, originalPrice: 149, rating: 4.8, reviewCount: 640, brand: "Orbit", colors: ["#111","#fff","#ff5b2e"], sizes: ["60%","75%","TKL"], inStock: true, stockCount: 60, isNew: true, isFeatured: true, salesCount: 720, tags: ["mechanical","rgb"], description: "Hot-swap mechanical keyboard with gasket mount." },
    { id: 7, name: "Halo Smart Bulb (4-pack)", category: "Electronics", subcategory: "Smart Home", price: 45, originalPrice: 60, rating: 4.3, reviewCount: 330, brand: "Halo", colors: ["#ffd166"], sizes: [], inStock: false, stockCount: 0, isNew: false, isFeatured: false, salesCount: 500, tags: ["smart-home","wifi"], description: "Color-changing Wi-Fi smart bulbs." },
    { id: 8, name: "Comet Gaming Mouse", category: "Electronics", subcategory: "Peripherals", price: 59, originalPrice: 69, rating: 4.4, reviewCount: 420, brand: "Orbit", colors: ["#111"], sizes: [], inStock: true, stockCount: 88, isNew: false, isFeatured: false, salesCount: 950, tags: ["gaming","wireless"], description: "Ultra-light 58g wireless gaming mouse." },

    // ---------- Fashion ----------
    { id: 9, name: "Everyday Merino Tee", category: "Fashion", subcategory: "Tops", price: 55, originalPrice: 75, rating: 4.5, reviewCount: 320, brand: "Northline", colors: ["#111","#e5e5e5","#5b6068","#1f2937"], sizes: ["XS","S","M","L","XL"], inStock: true, stockCount: 200, isNew: true, isFeatured: true, salesCount: 610, tags: ["merino","tee","essentials"], description: "Featherlight merino wool tee. Breathes in summer, warms in winter." },
    { id: 10, name: "Trailblazer Rain Jacket", category: "Fashion", subcategory: "Outerwear", price: 189, originalPrice: 220, rating: 4.6, reviewCount: 210, brand: "Northline", colors: ["#111","#16a34a","#ffd166"], sizes: ["S","M","L","XL"], inStock: true, stockCount: 44, isNew: false, isFeatured: true, salesCount: 300, tags: ["waterproof","hiking"], description: "3-layer waterproof shell with taped seams." },
    { id: 11, name: "Foundry Selvedge Jeans", category: "Fashion", subcategory: "Bottoms", price: 128, originalPrice: 160, rating: 4.4, reviewCount: 180, brand: "Foundry", colors: ["#1f2937","#111"], sizes: ["28","30","32","34","36"], inStock: true, stockCount: 60, isNew: false, isFeatured: false, salesCount: 420, tags: ["denim","japanese"], description: "14oz Japanese selvedge denim, tapered fit." },
    { id: 12, name: "Sunday Cashmere Beanie", category: "Fashion", subcategory: "Accessories", price: 42, originalPrice: 52, rating: 4.7, reviewCount: 96, brand: "Softwear", colors: ["#e5e5e5","#111","#5b6068"], sizes: ["One size"], inStock: true, stockCount: 150, isNew: true, isFeatured: false, salesCount: 210, tags: ["cashmere","winter"], description: "Buttery-soft 100% cashmere beanie." },
    { id: 13, name: "Meridian Leather Sneakers", category: "Fashion", subcategory: "Shoes", price: 165, originalPrice: 210, rating: 4.5, reviewCount: 275, brand: "Meridian", colors: ["#fff","#111","#5b6068"], sizes: ["7","8","9","10","11","12"], inStock: true, stockCount: 55, isNew: false, isFeatured: true, salesCount: 810, tags: ["leather","minimalist"], description: "Italian leather court sneakers, hand-lasted." },
    { id: 14, name: "Cabana Linen Shirt", category: "Fashion", subcategory: "Tops", price: 89, originalPrice: 110, rating: 4.3, reviewCount: 140, brand: "Softwear", colors: ["#fff","#ffd166","#5b6068"], sizes: ["S","M","L","XL"], inStock: true, stockCount: 90, isNew: true, isFeatured: false, salesCount: 260, tags: ["linen","summer"], description: "Relaxed-fit European linen shirt." },
    { id: 15, name: "Alloy Aviator Sunglasses", category: "Fashion", subcategory: "Accessories", price: 78, originalPrice: 95, rating: 4.2, reviewCount: 88, brand: "Alloy", colors: ["#111","#c0c0c0"], sizes: [], inStock: true, stockCount: 120, isNew: false, isFeatured: false, salesCount: 340, tags: ["sunglasses","uv-400"], description: "Polarized UV-400 aviators with titanium frame." },
    { id: 16, name: "Trekker Wool Socks (3-pack)", category: "Fashion", subcategory: "Accessories", price: 28, originalPrice: 36, rating: 4.8, reviewCount: 450, brand: "Northline", colors: ["#5b6068"], sizes: ["M","L"], inStock: true, stockCount: 300, isNew: false, isFeatured: false, salesCount: 900, tags: ["hiking","merino"], description: "Merino hiking socks with reinforced heel." },

    // ---------- Home & Kitchen ----------
    { id: 17, name: "Ember Cast-Iron Skillet 12\"", category: "Home & Kitchen", subcategory: "Cookware", price: 89, originalPrice: 110, rating: 4.9, reviewCount: 1500, brand: "Ember", colors: ["#111"], sizes: [], inStock: true, stockCount: 80, isNew: false, isFeatured: true, salesCount: 2200, tags: ["cast-iron","cookware"], description: "Pre-seasoned 12\" cast-iron skillet." },
    { id: 18, name: "Barista Espresso Machine", category: "Home & Kitchen", subcategory: "Appliances", price: 449, originalPrice: 549, rating: 4.5, reviewCount: 280, brand: "Barista", colors: ["#c0c0c0","#111"], sizes: [], inStock: true, stockCount: 15, isNew: true, isFeatured: true, salesCount: 340, tags: ["coffee","espresso"], description: "15-bar semi-automatic espresso machine with steam wand." },
    { id: 19, name: "Loom Waffle Bath Towels (Set of 2)", category: "Home & Kitchen", subcategory: "Bath", price: 68, originalPrice: 88, rating: 4.6, reviewCount: 320, brand: "Loom", colors: ["#fff","#ffd166","#5b6068"], sizes: [], inStock: true, stockCount: 140, isNew: false, isFeatured: false, salesCount: 500, tags: ["towels","cotton"], description: "Ultra-absorbent Turkish waffle-weave towels." },
    { id: 20, name: "Aurora Diffuser + 3 Oils", category: "Home & Kitchen", subcategory: "Wellness", price: 62, originalPrice: 78, rating: 4.4, reviewCount: 190, brand: "Aurora", colors: ["#fff","#111"], sizes: [], inStock: true, stockCount: 66, isNew: true, isFeatured: false, salesCount: 240, tags: ["aromatherapy"], description: "Ultrasonic diffuser with lavender, eucalyptus, citrus." },
    { id: 21, name: "Kettle & Chemex Bundle", category: "Home & Kitchen", subcategory: "Appliances", price: 175, originalPrice: 210, rating: 4.7, reviewCount: 210, brand: "Barista", colors: ["#111"], sizes: [], inStock: true, stockCount: 30, isNew: false, isFeatured: false, salesCount: 410, tags: ["coffee","pour-over"], description: "Gooseneck kettle + 6-cup Chemex + filters." },
    { id: 22, name: "Forge Chef Knife 8\"", category: "Home & Kitchen", subcategory: "Cookware", price: 129, originalPrice: 179, rating: 4.8, reviewCount: 640, brand: "Forge", colors: ["#111"], sizes: [], inStock: true, stockCount: 40, isNew: false, isFeatured: true, salesCount: 720, tags: ["chef-knife","damascus"], description: "67-layer Damascus steel chef's knife." },
    { id: 23, name: "Grove Ceramic Planter Trio", category: "Home & Kitchen", subcategory: "Decor", price: 48, originalPrice: 65, rating: 4.3, reviewCount: 78, brand: "Grove", colors: ["#fff","#111","#16a34a"], sizes: [], inStock: false, stockCount: 0, isNew: false, isFeatured: false, salesCount: 190, tags: ["planter","ceramic"], description: "Set of three handmade ceramic planters." },
    { id: 24, name: "Nordic Wool Throw Blanket", category: "Home & Kitchen", subcategory: "Decor", price: 145, originalPrice: 180, rating: 4.6, reviewCount: 140, brand: "Loom", colors: ["#e5e5e5","#5b6068","#ff5b2e"], sizes: [], inStock: true, stockCount: 50, isNew: true, isFeatured: false, salesCount: 220, tags: ["wool","home"], description: "Chunky-knit New Zealand wool throw." },

    // ---------- Books ----------
    { id: 25, name: "Atomic Habits", category: "Books", subcategory: "Non-fiction", price: 16, originalPrice: 22, rating: 4.8, reviewCount: 12000, brand: "Penguin", colors: [], sizes: [], inStock: true, stockCount: 500, isNew: false, isFeatured: true, salesCount: 8000, tags: ["self-help","bestseller"], description: "An easy & proven way to build good habits and break bad ones." },
    { id: 26, name: "The Midnight Library", category: "Books", subcategory: "Fiction", price: 14, originalPrice: 18, rating: 4.5, reviewCount: 5400, brand: "Viking", colors: [], sizes: [], inStock: true, stockCount: 300, isNew: false, isFeatured: false, salesCount: 4300, tags: ["novel","fiction"], description: "Matt Haig's beloved novel about lives untried." },
    { id: 27, name: "Deep Work", category: "Books", subcategory: "Non-fiction", price: 18, originalPrice: 24, rating: 4.7, reviewCount: 3200, brand: "Grand Central", colors: [], sizes: [], inStock: true, stockCount: 220, isNew: false, isFeatured: false, salesCount: 2600, tags: ["productivity"], description: "Rules for focused success in a distracted world." },
    { id: 28, name: "Project Hail Mary", category: "Books", subcategory: "Fiction", price: 15, originalPrice: 20, rating: 4.9, reviewCount: 8700, brand: "Ballantine", colors: [], sizes: [], inStock: true, stockCount: 180, isNew: true, isFeatured: true, salesCount: 5100, tags: ["scifi","novel"], description: "Andy Weir's genre-bending space adventure." },
    { id: 29, name: "The Design of Everyday Things", category: "Books", subcategory: "Design", price: 22, originalPrice: 28, rating: 4.6, reviewCount: 1900, brand: "Basic Books", colors: [], sizes: [], inStock: true, stockCount: 90, isNew: false, isFeatured: false, salesCount: 1500, tags: ["ux","design"], description: "Don Norman's classic on human-centered design." },
    { id: 30, name: "Sapiens", category: "Books", subcategory: "Non-fiction", price: 19, originalPrice: 26, rating: 4.5, reviewCount: 6200, brand: "Harper", colors: [], sizes: [], inStock: true, stockCount: 140, isNew: false, isFeatured: false, salesCount: 4200, tags: ["history","anthropology"], description: "A brief history of humankind by Yuval Noah Harari." },
    { id: 31, name: "The Pragmatic Programmer", category: "Books", subcategory: "Design", price: 32, originalPrice: 40, rating: 4.8, reviewCount: 2100, brand: "Addison-Wesley", colors: [], sizes: [], inStock: true, stockCount: 60, isNew: false, isFeatured: false, salesCount: 1800, tags: ["programming","dev"], description: "Your journey to mastery, 20th anniversary edition." },
    { id: 32, name: "Klara and the Sun", category: "Books", subcategory: "Fiction", price: 13, originalPrice: 17, rating: 4.2, reviewCount: 3400, brand: "Knopf", colors: [], sizes: [], inStock: false, stockCount: 0, isNew: true, isFeatured: false, salesCount: 2000, tags: ["novel","ai"], description: "Kazuo Ishiguro's tender AI parable." },

    // ---------- Sports ----------
    { id: 33, name: "Ascent Trail Running Shoes", category: "Sports", subcategory: "Footwear", price: 145, originalPrice: 175, rating: 4.6, reviewCount: 480, brand: "Ascent", colors: ["#111","#16a34a","#ff5b2e"], sizes: ["7","8","9","10","11","12"], inStock: true, stockCount: 88, isNew: true, isFeatured: true, salesCount: 640, tags: ["running","trail"], description: "Aggressive-lug trail runners with rock plate." },
    { id: 34, name: "Peak Yoga Mat 6mm", category: "Sports", subcategory: "Yoga", price: 68, originalPrice: 85, rating: 4.7, reviewCount: 720, brand: "Peak", colors: ["#5b6068","#111","#ff5b2e","#16a34a"], sizes: [], inStock: true, stockCount: 220, isNew: false, isFeatured: false, salesCount: 1400, tags: ["yoga","fitness"], description: "6mm eco-TPE mat with alignment marks." },
    { id: 35, name: "Torque Adjustable Dumbbells 55lb", category: "Sports", subcategory: "Strength", price: 349, originalPrice: 449, rating: 4.5, reviewCount: 320, brand: "Torque", colors: ["#111"], sizes: [], inStock: true, stockCount: 25, isNew: false, isFeatured: true, salesCount: 410, tags: ["home-gym","strength"], description: "Space-saving pair of 5-55lb adjustable dumbbells." },
    { id: 36, name: "Flow Insulated Water Bottle 24oz", category: "Sports", subcategory: "Hydration", price: 32, originalPrice: 42, rating: 4.8, reviewCount: 1900, brand: "Flow", colors: ["#111","#fff","#ff5b2e","#16a34a","#ffd166"], sizes: [], inStock: true, stockCount: 500, isNew: false, isFeatured: false, salesCount: 3500, tags: ["bottle","insulated"], description: "Vacuum-insulated stainless steel bottle." },
    { id: 37, name: "Summit 45L Hiking Backpack", category: "Sports", subcategory: "Backpacks", price: 165, originalPrice: 199, rating: 4.6, reviewCount: 260, brand: "Summit", colors: ["#5b6068","#16a34a","#ff5b2e"], sizes: [], inStock: true, stockCount: 40, isNew: true, isFeatured: false, salesCount: 380, tags: ["backpack","hiking"], description: "45L technical pack with rain cover." },
    { id: 38, name: "Rally Tennis Racquet Pro", category: "Sports", subcategory: "Racquet", price: 219, originalPrice: 259, rating: 4.4, reviewCount: 140, brand: "Rally", colors: ["#111","#ffd166"], sizes: ["4 1/4","4 3/8","4 1/2"], inStock: true, stockCount: 30, isNew: false, isFeatured: false, salesCount: 210, tags: ["tennis","racquet"], description: "300g graphite racquet, 100 sq in head." },
    { id: 39, name: "Cadence Bike Computer GPS", category: "Sports", subcategory: "Cycling", price: 189, originalPrice: 229, rating: 4.5, reviewCount: 190, brand: "Cadence", colors: ["#111"], sizes: [], inStock: true, stockCount: 45, isNew: false, isFeatured: false, salesCount: 280, tags: ["cycling","gps"], description: "Color-screen GPS cycling computer, 20h battery." },
    { id: 40, name: "Boulder Climbing Chalk Bag", category: "Sports", subcategory: "Climbing", price: 24, originalPrice: 32, rating: 4.3, reviewCount: 92, brand: "Boulder", colors: ["#ff5b2e","#111","#16a34a"], sizes: [], inStock: true, stockCount: 130, isNew: true, isFeatured: false, salesCount: 180, tags: ["climbing"], description: "Fleece-lined chalk bag with brush holster." },
  ];

  P.forEach((p, i) => {
    p.image = img(p.id);
    p.dateAdded = new Date(now - (P.length - i) * day * 3).toISOString();
  });

  window.PRODUCTS = P;
  window.CATEGORIES = [...new Set(P.map((p) => p.category))];
  window.BRANDS = [...new Set(P.map((p) => p.brand))].sort();
  window.ALL_COLORS = [...new Set(P.flatMap((p) => p.colors))];
  window.ALL_SIZES = [...new Set(P.flatMap((p) => p.sizes))];
})();
